### ISSUE TITLE
Is it integrate with Tacotron or DeepVoice ?

### ISSUE THREAD

**Issue by rishikksh20** [syang1993/FFTNet#1]
I haven't read FFTNet paper yet, but I had work on Wavenet which conditioned with Mel-spectrogram and easy integration with Tacotron. Is it possible same with FFTNet ?

**Comment by syang1993** [comment]
Hi, this FFTNet is used as vocoder, which is used to reconstruct audios as well as WaveNet vocoder. For now, the performance is not so good as WaveNet vocoder, I'm trying to improve it to get better performance.
